import { defineConfig } from 'vitepress'

const guideSidebar = [
  {
    text: 'Introduction',
    collapsed: false,
    items: [
      { text: 'Welcome', link: '/introduction/welcome' },
      { text: 'Who This Book Is For', link: '/introduction/who-this-book-is-for' },
      { text: 'How To Read This Book', link: '/introduction/how-to-read-this-book' },
    ],
  },
  {
    text: 'Part 0 — Desktop Fundamentals',
    collapsed: false,
    items: [
      { text: 'What Is a Desktop Shell?', link: '/part-0-fundamentals/what-is-a-desktop-shell' },
      { text: 'Wayland vs X11', link: '/part-0-fundamentals/wayland-vs-x11' },
      { text: 'Compositors vs Window Managers', link: '/part-0-fundamentals/compositors-vs-window-managers' },
      { text: 'Where Quickshell Fits', link: '/part-0-fundamentals/where-quickshell-fits' },
      { text: 'Why QML Instead of CSS', link: '/part-0-fundamentals/why-qml-instead-of-css' },
      { text: 'Declarative Programming', link: '/part-0-fundamentals/declarative-programming' },
      { text: 'Event-Driven UI', link: '/part-0-fundamentals/event-driven-ui' },
      { text: 'Installing Qt & Quickshell', link: '/part-0-fundamentals/installing-qt-and-quickshell' },
      { text: 'Your Development Environment', link: '/part-0-fundamentals/your-development-environment' },
      { text: 'First Launch', link: '/part-0-fundamentals/first-launch' },
    ],
  },
  {
    text: 'Part I — QML Fundamentals',
    collapsed: false,
    items: [
      { text: 'Hello World', link: '/part-1-qml/hello-world' },
      { text: 'Objects', link: '/part-1-qml/objects' },
      { text: 'Properties', link: '/part-1-qml/properties' },
      { text: 'IDs', link: '/part-1-qml/ids' },
      { text: 'Anchors', link: '/part-1-qml/anchors' },
      { text: 'Layouts', link: '/part-1-qml/layouts' },
      { text: 'Property Bindings', link: '/part-1-qml/property-bindings' },
      { text: 'JavaScript in QML', link: '/part-1-qml/javascript-in-qml' },
      { text: 'Signals', link: '/part-1-qml/signals' },
      { text: 'Components', link: '/part-1-qml/components' },
      { text: 'Models & Delegates', link: '/part-1-qml/models-and-delegates' },
      { text: 'Repeaters', link: '/part-1-qml/repeaters' },
      { text: 'ListView', link: '/part-1-qml/listview' },
      { text: 'MouseArea', link: '/part-1-qml/mousearea' },
      { text: 'Keys & Focus', link: '/part-1-qml/keys-and-focus' },
      { text: 'States', link: '/part-1-qml/states' },
      { text: 'Transitions', link: '/part-1-qml/transitions' },
      { text: 'Animations', link: '/part-1-qml/animations' },
      { text: 'Timers', link: '/part-1-qml/timers' },
      { text: 'Project: Build a Calculator', link: '/part-1-qml/project-calculator' },
    ],
  },
  {
    text: 'Part II — Understanding Quickshell',
    collapsed: false,
    items: [
      { text: 'What Quickshell Adds', link: '/part-2-quickshell/what-quickshell-adds' },
      { text: 'shell.qml and ShellRoot', link: '/part-2-quickshell/shell-qml-and-shellroot' },
      { text: 'Config Structure & Imports', link: '/part-2-quickshell/config-structure-and-imports' },
      { text: 'Hot Reload', link: '/part-2-quickshell/hot-reload' },
      { text: 'Multiple Configs', link: '/part-2-quickshell/multiple-configs' },
    ],
  },
  {
    text: 'Part III — Windows',
    collapsed: false,
    items: [
      { text: 'PanelWindow', link: '/part-3-windows/panel-window' },
      { text: 'FloatingWindow', link: '/part-3-windows/floating-window' },
      { text: 'PopupWindow', link: '/part-3-windows/popup-window' },
      { text: 'Layer Shell Concepts', link: '/part-3-windows/layer-shell-concepts' },
      { text: 'Anchors & Margins', link: '/part-3-windows/anchors-and-margins' },
      { text: 'Multi-Monitor Support', link: '/part-3-windows/multi-monitor-support' },
      { text: 'Exclusive Zones', link: '/part-3-windows/exclusive-zones' },
      { text: 'Transparency & Blur', link: '/part-3-windows/transparency-and-blur' },
      { text: 'Project: Build a Top Panel', link: '/part-3-windows/project-top-panel' },
    ],
  },
  {
    text: 'Part IV — Core Widgets',
    collapsed: false,
    items: [
      { text: 'Text, Icon, Button', link: '/part-4-widgets/text-icon-button' },
      { text: 'Clock', link: '/part-4-widgets/clock' },
      { text: 'Calendar', link: '/part-4-widgets/calendar' },
      { text: 'Battery', link: '/part-4-widgets/battery' },
      { text: 'CPU', link: '/part-4-widgets/cpu' },
      { text: 'RAM', link: '/part-4-widgets/ram' },
      { text: 'Disk', link: '/part-4-widgets/disk' },
      { text: 'Network', link: '/part-4-widgets/network' },
      { text: 'Volume', link: '/part-4-widgets/volume' },
      { text: 'Bluetooth', link: '/part-4-widgets/bluetooth' },
      { text: 'Brightness', link: '/part-4-widgets/brightness' },
      { text: 'Weather', link: '/part-4-widgets/weather' },
      { text: 'System Tray', link: '/part-4-widgets/system-tray' },
      { text: 'Notifications', link: '/part-4-widgets/notifications' },
      { text: 'Clipboard', link: '/part-4-widgets/clipboard' },
    ],
  },
  {
    text: 'Part V — Data & Services',
    collapsed: false,
    items: [
      { text: 'Processes & Shell Commands', link: '/part-5-services/processes-and-shell-commands' },
      { text: 'Parsing JSON', link: '/part-5-services/parsing-json' },
      { text: 'Reading & Watching Files', link: '/part-5-services/reading-and-watching-files' },
      { text: 'IPC', link: '/part-5-services/ipc' },
      { text: 'Timers Revisited', link: '/part-5-services/timers-revisited' },
      { text: 'HTTP Requests & Caching', link: '/part-5-services/http-requests-and-caching' },
      { text: 'Project: Build a Weather Widget', link: '/part-5-services/project-weather-widget' },
    ],
  },
  {
    text: 'Part VI — Linux Integration',
    collapsed: false,
    items: [
      { text: 'Hyprland', link: '/part-6-linux-integration/hyprland' },
      { text: 'Sway / i3', link: '/part-6-linux-integration/sway-i3' },
      { text: 'PipeWire', link: '/part-6-linux-integration/pipewire' },
      { text: 'MPRIS', link: '/part-6-linux-integration/mpris' },
      { text: 'UPower & Power Profiles', link: '/part-6-linux-integration/upower-and-power-profiles' },
      { text: 'BlueZ', link: '/part-6-linux-integration/bluez' },
      { text: 'Notifications Daemon', link: '/part-6-linux-integration/notifications-daemon' },
      { text: 'Clipboard Manager', link: '/part-6-linux-integration/clipboard-manager' },
      { text: 'Authentication (PAM/Greetd)', link: '/part-6-linux-integration/authentication' },
      { text: 'Display Managers', link: '/part-6-linux-integration/display-managers' },
    ],
  },
  {
    text: 'Part VII — Hyprland Deep Dive',
    collapsed: false,
    items: [
      { text: 'Workspaces', link: '/part-7-hyprland/workspaces' },
      { text: 'Active Window & Monitor', link: '/part-7-hyprland/active-window-and-monitor' },
      { text: 'Scratchpads', link: '/part-7-hyprland/scratchpads' },
      { text: 'IPC Events', link: '/part-7-hyprland/ipc-events' },
      { text: 'Project: Complete Workspace Switcher', link: '/part-7-hyprland/project-workspace-switcher' },
    ],
  },
  {
    text: 'Part VIII — Design System',
    collapsed: false,
    items: [
      { text: 'Typography', link: '/part-8-design-system/typography' },
      { text: 'Color Systems', link: '/part-8-design-system/color-systems' },
      { text: 'Material You, Gruvbox, Catppuccin', link: '/part-8-design-system/material-you-gruvbox-catppuccin' },
      { text: 'Spacing & Icons', link: '/part-8-design-system/spacing-and-icons' },
      { text: 'Shadows, Blur, Rounded Corners', link: '/part-8-design-system/shadows-blur-rounded-corners' },
      { text: 'Motion', link: '/part-8-design-system/motion' },
      { text: 'Accessibility', link: '/part-8-design-system/accessibility' },
      { text: 'Project: Design a Premium Panel', link: '/part-8-design-system/project-premium-panel' },
    ],
  },
  {
    text: 'Part IX — Building Applications',
    collapsed: false,
    items: [
      { text: 'App Launcher', link: '/part-9-applications/app-launcher' },
      { text: 'Dashboard', link: '/part-9-applications/dashboard' },
      { text: 'Notification Center', link: '/part-9-applications/notification-center' },
      { text: 'Power Menu', link: '/part-9-applications/power-menu' },
      { text: 'Lock Screen', link: '/part-9-applications/lock-screen' },
      { text: 'Media Player', link: '/part-9-applications/media-player' },
      { text: 'Emoji Picker', link: '/part-9-applications/emoji-picker' },
      { text: 'Clipboard Manager', link: '/part-9-applications/clipboard-manager' },
      { text: 'Control Center', link: '/part-9-applications/control-center' },
      { text: 'Network Menu', link: '/part-9-applications/network-menu' },
    ],
  },
  {
    text: 'Part X — Architecture at Scale',
    collapsed: false,
    items: [
      { text: 'Folder Structure', link: '/part-10-architecture/folder-structure' },
      { text: 'Components vs Services vs Utilities', link: '/part-10-architecture/components-vs-services-vs-utilities' },
      { text: 'Theming Systems', link: '/part-10-architecture/theming-systems' },
      { text: 'Configuration', link: '/part-10-architecture/configuration' },
      { text: 'State Management', link: '/part-10-architecture/state-management' },
      { text: 'Singletons', link: '/part-10-architecture/singletons' },
      { text: 'Performance Basics', link: '/part-10-architecture/performance-basics' },
    ],
  },
  {
    text: 'Part XI — Complete Desktop Shell',
    collapsed: false,
    items: [
      { text: 'Top Bar', link: '/part-11-complete-shell/top-bar' },
      { text: 'Dock', link: '/part-11-complete-shell/dock' },
      { text: 'Launcher', link: '/part-11-complete-shell/launcher' },
      { text: 'Notification Center', link: '/part-11-complete-shell/notification-center' },
      { text: 'Dashboard', link: '/part-11-complete-shell/dashboard' },
      { text: 'OSD', link: '/part-11-complete-shell/osd' },
      { text: 'Lock Screen', link: '/part-11-complete-shell/lock-screen' },
      { text: 'Login Manager', link: '/part-11-complete-shell/login-manager' },
      { text: 'Wallpaper Manager', link: '/part-11-complete-shell/wallpaper-manager' },
      { text: 'Settings App', link: '/part-11-complete-shell/settings-app' },
      { text: 'Audio Controls', link: '/part-11-complete-shell/audio-controls' },
      { text: 'Bluetooth Manager', link: '/part-11-complete-shell/bluetooth-manager' },
      { text: 'Keyboard Shortcuts', link: '/part-11-complete-shell/keyboard-shortcuts' },
      { text: 'Multi-Monitor', link: '/part-11-complete-shell/multi-monitor' },
      { text: 'Notification Daemon', link: '/part-11-complete-shell/notification-daemon' },
      { text: 'Power Profiles', link: '/part-11-complete-shell/power-profiles' },
      { text: 'Session Management', link: '/part-11-complete-shell/session-management' },
      { text: 'Startup', link: '/part-11-complete-shell/startup' },
      { text: 'Window Switcher', link: '/part-11-complete-shell/window-switcher' },
      { text: 'Workspace Indicator', link: '/part-11-complete-shell/workspace-indicator' },
    ],
  },
  {
    text: 'Part XII — Advanced Quickshell',
    collapsed: false,
    items: [
      { text: 'Performance Profiling', link: '/part-12-advanced/performance-profiling' },
      { text: 'Memory Optimization', link: '/part-12-advanced/memory-optimization' },
      { text: 'Lazy Loading', link: '/part-12-advanced/lazy-loading' },
      { text: 'Custom Modules', link: '/part-12-advanced/custom-modules' },
      { text: 'Packaging & Distribution', link: '/part-12-advanced/packaging-and-distribution' },
      { text: 'Testing & Debugging', link: '/part-12-advanced/testing-and-debugging' },
      { text: 'Logging', link: '/part-12-advanced/logging' },
      { text: 'Custom Services', link: '/part-12-advanced/custom-services' },
      { text: 'D-Bus Integration', link: '/part-12-advanced/dbus-integration' },
      { text: 'QML Extensions', link: '/part-12-advanced/qml-extensions' },
      { text: 'Testing', link: '/part-12-advanced/testing' },
      { text: 'Debugging', link: '/part-12-advanced/debugging' },
      { text: 'Distribution', link: '/part-12-advanced/distribution' },
      { text: 'Contributing', link: '/part-12-advanced/contributing' },
    ],
  },
  {
    text: 'Part XIII — Source Code Tour',
    collapsed: false,
    items: [
      { text: 'Reading Caelestia', link: '/part-13-source-tour/reading-caelestia' },
      { text: "Reading Illogical-Impulse's Config", link: '/part-13-source-tour/reading-illogical-impulse' },
      { text: "Reading Outfoxxed's Config", link: '/part-13-source-tour/reading-outfoxxed' },
      { text: 'Other Community Shells', link: '/part-13-source-tour/other-community-shells' },
      { text: 'Architecture Overview', link: '/part-13-source-tour/architecture-overview' },
      { text: 'Core Types', link: '/part-13-source-tour/core-types' },
      { text: 'Window System', link: '/part-13-source-tour/window-system' },
      { text: 'Service Ecosystem', link: '/part-13-source-tour/service-ecosystem' },
    ],
  },
  {
    text: 'Appendix',
    collapsed: false,
    items: [
      { text: 'QML Cheatsheet', link: '/appendix/qml-cheatsheet' },
      { text: 'Every Quickshell Type', link: '/appendix/every-quickshell-type' },
      { text: 'Common Errors', link: '/appendix/common-errors' },
      { text: 'Debugging Guide', link: '/appendix/debugging-guide' },
      { text: 'FAQ', link: '/appendix/faq' },
      { text: 'Architecture Diagrams', link: '/appendix/architecture-diagrams' },
      { text: 'Configuration Samples', link: '/appendix/configuration-samples' },
      { text: 'Further Reading', link: '/appendix/further-reading' },
      { text: 'Glossary', link: '/appendix/glossary' },
      { text: 'Migration Guide', link: '/appendix/migration-guide' },
      { text: 'Troubleshooting', link: '/appendix/troubleshooting' },
    ],
  },
]

export default defineConfig({
  lang: 'en-US',
  title: 'The Quickshell Book',
  description: 'A comprehensive guide to building desktop shells with Quickshell and QML',
  base: '/the_quickshell_book/',
  srcDir: '.',

  cleanUrls: true,
  lastUpdated: true,

  head: [
    ['link', { rel: 'preconnect', href: 'https://fonts.googleapis.com' }],
    ['link', { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' }],
    ['link', { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap' }],
    ['link', { rel: 'icon', href: '/favicon.svg', type: 'image/svg+xml' }],
  ],

  themeConfig: {
    logo: '/favicon.svg',
    siteTitle: 'The Quickshell Book',

    nav: [
      { text: 'Home', link: '/' },
      { text: 'Guide', link: '/introduction/welcome', activeMatch: '^/(introduction|part-)' },
      { text: 'Examples', link: 'https://github.com/programmersd21/the_quickshell_book/tree/main/examples' },
    ],

    sidebar: {
      '/': guideSidebar,
    },

    docFooter: {
      prev: 'Previous',
      next: 'Next',
    },

    search: {
      provider: 'local',
    },

    editLink: {
      pattern: 'https://github.com/programmersd21/the_quickshell_book/edit/main/docs/:path',
      text: 'Edit this page on GitHub',
    },

    footer: {
      message: 'Built with VitePress. Licensed under MIT.',
      copyright: '© 2026 The Quickshell Book Authors',
    },

    socialLinks: [
      { icon: 'github', link: 'https://github.com/programmersd21/the_quickshell_book' },
    ],
  },

  vite: {
    plugins: [],
  },
})
